openapi: 3.0.3
servers:
  - url: "http://localhost:3000"
info:
  title: WASAText
  description: WASAText project
  version: 1.0.0
paths:
  /session:
    post:
      tags: ["Login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema: { $ref: "#/components/schemas/Username" }
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema: { $ref: "#/components/schemas/UserID" }
        '400': { $ref: "#/components/responses/BadRequest" }
        '500': { $ref: "#/components/responses/InternalServerError" }

  /users:
    parameters:
      - name: search
        in: query
        description: The username (or a part of it) to search.
        schema: { $ref: "#/components/schemas/Username" }
        required: true

    get:
      tags: ["User"]
      operationId: searchUsers
      summary: Get the list of users
      description: |-
        Get the list of Users that match with the username specified in the query.
      
      responses:
        '200':
          description: List of registered users
          content:
            application/json:
              schema: { $ref: "#/components/schemas/UsersList" }
        '400': { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Unauthorized" }
        '403': { $ref: "#/components/responses/Forbidden" }
        '500': { $ref: "#/components/responses/InternalServerError" }
      
      security:
        - bearerAuth: []

  /users/{userId}:
    patch:
      tags: ["User"]
      summary: Set my username
      operationId: setMyUserName
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/Username" }
      responses:
        '204': { description: Username updated successfully }
        '400': { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Unauthorized" }
        '403': { $ref: "#/components/responses/Forbidden" }
        '500': { $ref: "#/components/responses/InternalServerError" }
  
  /users/{userId}/photo:
    patch:
      tags: ["User"]
      summary: Set my profile photo
      operationId: setMyPhoto
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/Photo" }              
      responses:
        '204': { description: Profile photo updated successfully }
        '400': { $ref: "#/components/responses/BadRequest" }
        '403': { $ref: "#/components/responses/Forbidden" }
        '500': { $ref: "#/components/responses/InternalServerError" }

  /users/{userId}/conversations:
    get:
      tags: ["Conversations"]
      summary: Get user's conversations
      operationId: getMyConversations
      responses:
        '200':
          description: List of conversations
        '400': { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Unauthorized" }
        '403': { $ref: "#/components/responses/Forbidden" }
        '500': { $ref: "#/components/responses/InternalServerError" }

  /users/{userId}/conversations/{ConversationId}:
    get:
      tags: ["Conversations"]
      summary: Get a conversation by ID
      operationId: getConversation
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Conversation details
        '400': { $ref: "#/components/responses/BadRequest" }
        '500': { $ref: "#/components/responses/InternalServerError" }
  
  /users/{userId}/messages:
    post:
      tags: ["Messages"]
      summary: Send a new message
      operationId: sendMessage
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/Message" }
      responses:
        '201':
          description: Message sent successfully
        '400': { $ref: "#/components/responses/BadRequest" }
        '500': { $ref: "#/components/responses/InternalServerError" }

  /users/{userId}/messages/{MessageId}/forward:
    post:
      tags: ["messages"]
      summary: Forward a message
      operationId: forwardMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newConversationId:
                  type: string
                  example: "conv456"
      responses:
        '200':
          description: Message forwarded successfully
        '400': { $ref: "#/components/responses/BadRequest" }
        '500': { $ref: "#/components/responses/InternalServerError" }

  /users/{userId}/messages/{MessageId}/comment:
    post:
      tags: ["Messages"]
      summary: Comment on a message
      operationId: commentMessage
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/Comment" }
      responses:
        '201':
          description: Comment added successfully
        '400': { $ref: "#/components/responses/BadRequest" }
        '500': { $ref: "#/components/responses/InternalServerError" }

    delete:
      tags: ["Messages"]
      summary: Remove a comment from a message
      operationId: uncommentMessage
      parameters:
        - name: MessageId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Comment removed successfully
        '400': { $ref: "#/components/responses/BadRequest" }
        '500': { $ref: "#/components/responses/InternalServerError" }

  /users/{userId}/messages/{MessageId}:
    delete:
      tags: ["Messages"]
      summary: Delete a message
      operationId: deleteMessage
      parameters:
        - name: MessageId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Message deleted successfully
        '400': { $ref: "#/components/responses/BadRequest" }
        '500': { $ref: "#/components/responses/InternalServerError" }

  /users/{userId}/groups:
    post:
      tags: ["groups"]
      summary: Add user to group
      operationId: addToGroup
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/User" }
      responses:
        '200':
          description: User added to group successfully
        '400': { $ref: "#/components/responses/BadRequest" }
        '500': { $ref: "#/components/responses/InternalServerError" }

  /users/{userId}/groups/{groupId}:
    delete:
      tags: ["groups"]
      summary: Leave a group
      operationId: leaveGroup
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully left the group
        '400': { $ref: "#/components/responses/BadRequest" }
        '500': { $ref: "#/components/responses/InternalServerError" }

  /users/{userId}/groups/{groupId}/name:
    patch:
      tags: ["groups"]
      summary: Set group name
      operationId: setGroupName
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                groupName: { $ref: "#/components/schemas/GroupName" }
      responses:
        '200':
          description: Group name updated successfully
        '400': { $ref: "#/components/responses/BadRequest" }
        '500': { $ref: "#/components/responses/InternalServerError" }

  /users/{userId}/groups/{groupId}/photo:
    patch:
      tags: ["groups"]
      summary: Set group photo
      operationId: setGroupPhoto
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/Photo" }
      responses:
        '200':
          description: Group photo updated successfully
        '400': { $ref: "#/components/responses/BadRequest" }
        '500': { $ref: "#/components/responses/InternalServerError" }


components:
  schemas:
    Username: #Rappresenta l'username dell'utente
      description: A user's nickname
      type: object
      properties:
        name:
          description: Any string between 3 and 16 chars
          type: string 
          example: "Maria"
          pattern: '^.*?$'
          minLength: 3 
          maxLength: 16

    UserID: #Rappresenta l'identificativo dell'utente
      description: A user's id
      type: integer
      example: 123456

    User:
      description: Represent a user
      type: object
      properties:
        userId: { $ref: "#/components/schemas/UserID" }
        username: { $ref: "#/components/schemas/Username" }

    UsersList:
      title: Users List
      description: |-
        A list of users for many responses.
        It's used to get a list of users for the search 
      type: array
      items:
        type: object
        description: User
        properties:
          user: { $ref: "#/components/schemas/User" }
      minItems: 0
      maxItems: 100
      
    GroupName:
      description: A group name
      type: object
      properties:
        name:
          description: Any string between 1 and 16
          type: string
          example: "WasaGroup 24/25"
          pattern: '^.*?$'
          minLength: 1
          maxLength: 16

    GroupID: 
      description: A group's id
      type: integer
      example: 123456

    Group:
      description: Represent a group
      type: object
      properties:
        groupId: { $ref: "#/components/schemas/GroupID" }
        groupName: { $ref: "#/components/schemas/GroupName" }
        UserList: { $ref: "#/components/schemas/UsersList" }

    Photo: 
      description: Represent a photo
      type: object
      properties:
        photoUrl:
          type: string
          format: uri
          example: "https://example.com/photo.jpg"

    Message:
      description: Represent a message 
      type: string
      example: "Hi!"
      pattern: '^.*?$'
      minLength: 1
      maxLength: 500

    MessageID:
      description: A message's id
      type: integer
      example: 123456

    Comment:
      description: Represent a comment
      type: string
      example: "🌐"
      pattern: '^[\u1F300-\u1F6FF\u1F900-\u1F9FF\u2600-\u26FF\u2700-\u27BF\uFE0F]+$'

    CommentID:
      description: A comment's id
      type: integer
      example: 123456

#    Messages:
#      type: object
#      properties:
#        conversationId: { $ref: "#/components/schemas/ConversationID" }
#        sender: { $ref: "#/components/schemas/User" }
#        content : { $ref: "#/components/schemas/Message" }
#        timestamp: {$ref: "#/components/schemas/Timestamp" }    

    Conversation:
      description: Represent a conversation, includes foto, messages and comments
      type: object
      properties:
        photo: { $ref: "#/components/schemas/Photo" }        
        conversationId: { $ref: "#/components/schemas/ConversationID" }
        sender: { $ref: "#/components/schemas/User" }
        content : { $ref: "#/components/schemas/Message" }
        comment: {$ref: "#/components/schemas/Comment"}
        timestamp: {$ref: "#/components/schemas/Timestamp" }        

    ConversationID:
      description: A message's id 
      type: integer
      example: 123456

    listOfConversations:
      description: Represent a list of conversations
      type: array
      minItems: 0
      maxItems: 64
      items: { $ref: "#/components/schemas/Conversation" }

    Timestamp:
      title: Timestamp
      description: The timestamp of the message.
      type: string
      format: date-time
      pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}$"
      example: "2024-12-31T23:59:59"
      minLength: 19
      maxLength: 19

    StatusInfo:
      title: Status Info
      type: object
      properties:
        status:
          type: string
          enum:
            - info
            - warning
            - critical
            - ""
        title: { type: string }
        message: { type: string }
        url: { type: string }
    

  responses:
    Unauthorized: #401
      description: The access token is missing or it's expired

    BadRequest: #400
      description: The request was not compliant with the documentation (eg. missing fields, etc)
    
    Forbidden: #403
      description: The user is not allowed to perform the action.

    InternalServerError: #500
      description: The server encountered an internal error. Further info in server logs

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
